extract:
    nix-shell -p yq-go --run 'yq eval-all -o toml ". as \$item ireduce ({}; . * \$item)" ./settings.toml ~/.local/state/noctalia/settings.toml' > merged.toml
    mv merged.toml settings.toml
