config_version = 8

[bar.default]
center = [ "audio_visualizer_1", "clipboard", "clock", "notifications", "audio_visualizer_2" ]
end = [ "tray", "bluetooth", "network", "volume", "brightness", "battery", "session" ]
start = [ "workspaces", "cpu", "ram", "temp" ]
widget_spacing = 14

[control_center]
sidebar = "full"
sidebar_section = "full"

[shell]
font_family = "JetBrainsMono NF"
lang = "en"

    [shell.panel]
    borders = false
    control_center_placement = "floating"
    open_near_click_control_center = true
    transparency_mode = "soft"

[widget.audio_visualizer]
bands = 128
show_when_idle = true
width = 400

[widget.audio_visualizer_1]
bands = 128
interactive = false
type = "audio_visualizer"
width = 400

[widget.audio_visualizer_2]
bands = 128
interactive = false
type = "audio_visualizer"
width = 400

[widget.clock]
format = "{:%A, %B %d - %H:%M:%S}"

[widget.cpu]
display = "graph"

[widget.network]
show_label = false

[widget.workspaces]
display = "none"