config_version = 14

[bar.default]
background_opacity = 0.5999999865889549
center = [
  "power_profile",
  "clock",
  "notifications",
]
concave_edge_corners = false
end = [
  "tray",
  "bluetooth",
  "network",
  "settings",
  "brightness",
  "volume",
  "battery",
  "session",
]
margin_edge = 6
margin_ends = 6
start = [
  "workspaces",
  "network_rx",
  "network_tx",
  "cpu",
  "ram",
  "temp",
]
widget_spacing = 14

[calendar]
enabled = true

[control_center]
hidden_tabs = [
  "weather",
  "screen-time",
]
sidebar = "full"
sidebar_section = "full"

[hooks]
session_locked = "lock-keyring"

[idle]
behavior_order = [
  "lock",
  "Screen Off (On Battery)",
]
pre_action_fade_seconds = 5

[idle.behavior."Screen Off (On Battery)"]
action = "command"
command = "sh -c 'if [ $(cat /sys/class/power_supply/AC*/online 2>/dev/null | grep -c 1) -eq 0 ]; then niri msg action power-off-monitors; fi'"
enabled = true
timeout = 660.0

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600.0

[lockscreen]
blurred_desktop = true

[nightlight]
enabled = true
force = false
temperature_night = 3000

[notification]
background_opacity = 0.7499999832361937
border = false
position = "top_center"

[osd]
border = false

[plugins]
auto_update = "none"
enabled = ["noctalia/notes"]

[shell]
button_borders = false
card_borders = false
font_family = "JetBrainsMono NF"
input_borders = false
lang = "en"
password_style = "random"
polkit_agent = true
popup_borders = false

[shell.panel]
borders = false
control_center_placement = "floating"
open_near_click_control_center = true
open_near_click_session = true
transparency_mode = "soft"

[shell.screen_corners]
enabled = true

[theme]
custom_palette = "Cream"
source = "custom"

[widget.clock]
anchor = true
format = "{:%A, %B %d - %H:%M:%S}"

[widget.cpu]
label_min_width = 32
visualization = "graph"

[widget.network]
show_label = false

[widget.network_rx]
label_min_width = 48
network_speed_compact = true
network_speed_unit = "mb"
visualization = "graph"

[widget.network_tx]
label_min_width = 48
network_speed_compact = true
visualization = "graph"

[widget.ram]
visualization = "graph"

[widget.tray]
hidden = ["vicinae"]

[widget.workspaces]
show_labels = false

[wallpaper]
enabled = false
