host := `hostname -s`

help:
    @just --list

default:
    @just help

update:
    nix flake update --flake .
    @echo -e "\033[1;32mUPDATE COMPLETE\033[0m"

inspect:
    nix repl .

vm host=host *args:
    nixos-rebuild --flake '.#{{ host }}' build-vm {{ args }}
    ./result/bin/run-nixos-vm

build host=host *args:
    nixos-rebuild --flake '.#{{ host }}' dry-build {{ args }}
