host := `hostname -s`

help:
    @just --list

default:
    @just help

update:
    nix flake update --flake .
    @echo -e "\033[1;32mUPDATE COMPLETE\033[0m"

inspect:
    nix repl .

build-vm host=host *args:
    @nixos-rebuild --flake '.#{{ host }}' build-vm {{ args }}
    @gum confirm "Launch VM now?" --default="No"
    @just start-vm

start-vm:
    ./result/bin/run-*-vm

build host=host *args:
    nixos-rebuild --flake '.#{{ host }}' dry-build {{ args }}
