host := `hostname -s`

help:
    @just --list

default:
    @just help

update:
    nix flake update --flake .
    @echo -e "\033[1;32mUPDATE COMPLETE\033[0m"

inspect target=".":
    nix repl '{{ target }}'

build host=host *args:
    nixos-rebuild --flake '.#{{ host }}' dry-build {{ args }}
